/*
 * A733 (sun60iw2) SoC register definitions, E902 view.
 *
 * All addresses verified against:
 *   doc/A733_User Manual_V0.91.pdf  ch.2 (memory map), 4.2.5 (PRCM), 6.1 (MSGBOX), 18.10 (UART)
 *   kernel bsp/drivers/clk/sunxi-ng/ccu-sun60iw2-r.c  (clock gate offsets)
 */
#ifndef __A733_H__
#define __A733_H__

typedef unsigned int   u32;
typedef unsigned char  u8;

#define readl(a)	(*(volatile u32 *)(a))
#define writel(v, a)	(*(volatile u32 *)(a) = (u32)(v))
#define readb(a)	(*(volatile u8  *)(a))
#define writeb(v, a)	(*(volatile u8  *)(a) = (u8)(v))

/* ---- SRAM_A2: E902 view 0x40000000..0x40033FFF, 208K (manual ch.2) ---- */
#define SRAM_A2_BASE		0x40000000
#define SRAM_A2_SIZE		0x00034000
#define FW_LOAD_ADDR		0x40014000	/* E902_RST_START_ADDR default */

/* ---- R-CCU / S_PRCM: 0x07010000, 64K (manual ch.2 "S_PRCM") ---- */
#define R_CCU_BASE		0x07010000
#define R_APBS0_CLK_REG		(R_CCU_BASE + 0x000C)
#define R_APBS1_CLK_REG		(R_CCU_BASE + 0x0010)
#define S_MBOX_BGR_REG		(R_CCU_BASE + 0x017C)	/* bit16 rst, bit0 gating */
#define S_UART_BGR_REG		(R_CCU_BASE + 0x018C)	/* bit17/16 rst, bit1/0 gating */
#define RISCV_24M_CLK_REG	(R_CCU_BASE + 0x0210)
#define RISCV_BGR_REG		(R_CCU_BASE + 0x021C)

/* APBSx_CLK_REG fields (manual 4.2.5.2 / 4.2.5.3) */
#define APBS_SRC_SHIFT		24
#define APBS_SRC_MASK		0x7
#define APBS_M_SHIFT		0
#define APBS_M_MASK		0x1F
#define APBS_SRC_DCXO		0	/* crystal: 26 MHz on this board (T31/T34) */
#define APBS_SRC_RTC32K		1
#define APBS_SRC_RC16M		2
#define APBS_SRC_PERIPLL_DIV	3	/* 200 MHz */
#define APBS_SRC_SYS_CLK24M	4	/* 24 MHz, regenerated by pll-ref from the 26 MHz crystal */

#define FREQ_DCXO		26000000u	/* board crystal is 26 MHz (schematic Y1, T34); NOT 24 */
#define FREQ_SYS_CLK24M		24000000u	/* internal 24M (R-CCU mux 4); shared timestamp ticks here (T31: 23.9999 MHz) */
#define FREQ_RTC32K		32768u
#define FREQ_RC16M		16000000u
#define FREQ_PERIPLL_DIV	200000000u

/* ---- E902 CFG: 0x07032000, 4K (manual 5.2.3) ---- */
#define E902_CFG_BASE		0x07032000
#define E902_AUTO_GATING_REG	(E902_CFG_BASE + 0x0004)
#define E902_DDR_REMAP_REG	(E902_CFG_BASE + 0x0020)
#define E902_WAKEUP_IRQ_NUM_REG	(E902_CFG_BASE + 0x0060)
#define E902_WAKEUP_MASK0_REG	(E902_CFG_BASE + 0x0064)	/* bit0 = irq 16 */
#define E902_WAKEUP_MASK1_REG	(E902_CFG_BASE + 0x0068)	/* bit0 = irq 48 */
#define E902_PAD_LPMD_REG	(E902_CFG_BASE + 0x0080)
#define E902_RST_START_ADDR_REG	(E902_CFG_BASE + 0x0204)

/* ---- S_TIMER: 0x07091000, 4K (manual ch.2; registers 8.2.6/8.2.7) ----
 * Four independent down-counters. Clock source is selectable per timer
 * between RTC_32K and SYS_CLK24M, with a /1../128 prescaler.
 */
#define S_TIMER_BASE		0x07091000
#define S_TIMER_BGR_REG		(R_CCU_BASE + 0x011C)	/* bit16 rst, bit0 gating */

#define TMR_IRQ_EN_REG		(S_TIMER_BASE + 0x0000)
#define TMR_IRQ_STA_REG		(S_TIMER_BASE + 0x0004)
/*
 * n = 0..3; per-timer block is 0x20 apart starting at 0x20.
 *
 * NOT the layout in manual 8.2.6 -- that table is the CPUX-domain timer
 * (0x02052000: blocks at 0x10, 0x20, ...). Measured on the board
 * 2026-09-23 (FINDINGS-LEDGER T30): 0x10..0x1C are read-as-zero/write-
 * ignored; the block at 0x20 raises IRQ_STA bit0, the one at 0x40 bit1
 * (and CLIC irq 21). The vendor scp.fex agrees: timer 0 at 0x07091020
 * (sw zero,32(a3) @0x4000645c), interval registers at +0x24 / +0x44.
 */
#define TMR_CTRL_REG(n)		(S_TIMER_BASE + 0x0020 + 0x20 * (n))
#define TMR_INTV_VALUE_REG(n)	(S_TIMER_BASE + 0x0024 + 0x20 * (n))
#define TMR_CUR_VALUE_REG(n)	(S_TIMER_BASE + 0x0028 + 0x20 * (n))

/* Per-timer counter clock in R-CCU (ccu-sun60iw2-r.c r_timer0..3_clk):
 * bit0 enable, bits[3:1] power-of-two divider, bits[6:4] mux (0 = dcxo).
 * Reset value 0 = clock OFF: without it the counter never moves (RELOAD
 * never self-clears). The vendor writes it next to every timer setup. */
#define R_TIMER_CLK_REG(n)	(R_CCU_BASE + 0x0100 + 4 * (n))
#define R_TIMER_CLK_EN		(1u << 0)
/* mux = r_timer_parents[4] = pll-ref, 24 MHz. dcxo (index 0) is 26 MHz on
 * the Zero 3W: measured 10.857 ticks/s instead of 10 with it (T31). */
#define R_TIMER_CLK_PLL_REF	(4u << 4)

#define TMR_IRQ_EN(n)		(1u << (n))
#define TMR_IRQ_PEND(n)		(1u << (n))

/* TMR_CTRL_REG fields (manual 8.2.7.3) */
#define TMR_CTRL_EN		(1u << 0)	/* 1 = start */
#define TMR_CTRL_RELOAD		(1u << 1)	/* 1 = reload interval; self-clearing */
#define TMR_CTRL_SRC_SHIFT	2
#define TMR_CTRL_SRC_RTC32K	(0u << TMR_CTRL_SRC_SHIFT)
#define TMR_CTRL_SRC_24M	(1u << TMR_CTRL_SRC_SHIFT)	/* reset default */
#define TMR_CTRL_PRES_SHIFT	4		/* 000=/1 .. 111=/128 */
#define TMR_CTRL_MODE_CONT	(0u << 7)	/* keeps running */
#define TMR_CTRL_MODE_SINGLE	(1u << 7)	/* auto-disables at zero */

/* ---- S_UART0: 0x07080000, 4K (manual ch.2, regs 18.10.8) ---- */
#define S_UART0_BASE		0x07080000
#define S_UART1_BASE		0x07081000
#define UART_RBR		0x0000	/* R, DLAB=0 */
#define UART_THR		0x0000	/* W, DLAB=0 */
#define UART_DLL		0x0000	/* RW, DLAB=1 */
#define UART_DLH		0x0004	/* RW, DLAB=1 */
#define UART_IER		0x0004	/* RW, DLAB=0 */
#define UART_IIR		0x0008	/* R */
#define UART_FCR		0x0008	/* W */
#define UART_LCR		0x000C
#define UART_MCR		0x0010
#define UART_LSR		0x0014
#define UART_USR		0x007C
#define UART_TFL		0x0080
#define UART_RFL		0x0084
#define UART_HALT		0x00A4

#define LCR_DLAB		(1u << 7)
#define LCR_WLS_8BIT		0x3	/* bits[1:0] */
#define LCR_STOP_1BIT		0	/* bit2 = 0 */
#define FCR_FIFOE		(1u << 0)
#define FCR_RFIFOR		(1u << 1)
#define FCR_XFIFOR		(1u << 2)
#define LSR_DR			(1u << 0)	/* data ready */
#define LSR_THRE		(1u << 5)	/* THR empty */
#define LSR_TEMT		(1u << 6)	/* transmitter empty */
#define IER_ERBFI		(1u << 0)	/* rx data available int */

/* ---- MSGBOX (manual 6.1.6) ----
 * MBOX_CPUX: CPUS writes, CPUX reads   -> E902 to ARM
 * MBOX_CPUS: CPUX writes, CPUS reads   -> ARM to E902
 * 4 channels, FIFO depth 8 x 32bit each.
 */
#define MBOX_CPUX_BASE		0x03004000	/* we WRITE here  */
#define MBOX_CPUS_BASE		0x07094000	/* we READ here   */
#define MBOX_N			0		/* only one peer on A733 */

#define MBOX_RD_IRQ_EN(b)	((b) + 0x0020 + 0x100 * MBOX_N)
#define MBOX_RD_IRQ_STAT(b)	((b) + 0x0024 + 0x100 * MBOX_N)
#define MBOX_WR_IRQ_EN(b)	((b) + 0x0030 + 0x100 * MBOX_N)
#define MBOX_WR_IRQ_STAT(b)	((b) + 0x0034 + 0x100 * MBOX_N)
#define MBOX_FIFO_STATUS(b, p)	((b) + 0x0050 + 0x100 * MBOX_N + 4 * (p))
#define MBOX_MSG_STATUS(b, p)	((b) + 0x0060 + 0x100 * MBOX_N + 4 * (p))
#define MBOX_MSG(b, p)		((b) + 0x0070 + 0x100 * MBOX_N + 4 * (p))
#define MBOX_WR_IRQ_THR(b, p)	((b) + 0x0080 + 0x100 * MBOX_N + 4 * (p))

#define MBOX_RD_IRQ_EN_BIT(p)	(1u << ((p) * 2))
#define MBOX_RD_IRQ_PEND_BIT(p)	(1u << ((p) * 2))
#define MBOX_FIFO_FULL		(1u << 0)
#define MBOX_MSG_NUM_MASK	0xF

/* ---- Main CCU: 0x02002000, 16K (manual ch.2) ----
 * MBOX_CPUX lives in the CPUX power domain; its gate is here.
 * Offsets from bsp/drivers/clk/sunxi-ng/ccu-sun60iw2.c:751 and :2087.
 */
#define CCU_BASE		0x02002000
#define CCU_MSGBOX_BGR_REG	(CCU_BASE + 0x0744)	/* bit16 rst, bit0 gating */

/* ---- CLIC: TCIP fixed at 0xE0000000..0xEFFFFFFF, core-internal.
 * Base 0xE0800000 confirmed from E902 manual 10.2 and from scp.fex
 * (lui a4,0xe0801 constructing CLICINTIE[0] at 0xE0801001).
 */
#define CLIC_BASE		0xE0800000
#define CLIC_CFG		(CLIC_BASE + 0x0000)
#define CLIC_INFO		(CLIC_BASE + 0x0004)
#define CLIC_MINTTHRESH		(CLIC_BASE + 0x0008)
#define CLIC_INTIP(i)		(CLIC_BASE + 0x1000 + 4 * (i))
#define CLIC_INTIE(i)		(CLIC_BASE + 0x1001 + 4 * (i))
#define CLIC_INTATTR(i)		(CLIC_BASE + 0x1002 + 4 * (i))
#define CLIC_INTCTL(i)		(CLIC_BASE + 0x1003 + 4 * (i))

#define CLIC_INTATTR_VECTORED	(1u << 0)
#define CLIC_INTATTR_TRIG_LEVEL	(0u << 1)
#define CLIC_INTATTR_TRIG_EDGE	(1u << 1)

/* ---- Interrupt numbers, E902 view (manual Table 12-2) ---- */
#define IRQ_S_UART0		29
#define IRQ_S_UART1		30
#define IRQ_S_TWI0		31
#define IRQ_GPIOL_S		25
#define IRQ_GPIOL_NS		26
#define IRQ_S_TIMER0		20
#define IRQ_S_TIMER1		21
#define IRQ_S_TIMER2		22
#define IRQ_S_TIMER3		23
#define IRQ_CPUS_MBOX_READ	39	/* CPUS MSGBOX READ IRQ    */
#define IRQ_CPUX_MBOX_W_R	48	/* ARM wrote to MBOX_CPUS  */

#endif /* __A733_H__ */
