#include <stddef.h>
#include "isp_tuning_priv.h"
#define O(name, type, field) char name[offsetof(type, field) + 1];
#define S(name, type) char name[sizeof(type) + 1];
S(sz_test, struct isp_test_param)
S(sz_3a, struct isp_3a_param)
S(sz_tune, struct isp_tunning_param)
S(sz_iso, struct isp_dynamic_param)
S(sz_all, struct isp_param_config)
S(sz_dyncfg, struct isp_dynamic_config)
O(o_test_ae_en, struct isp_test_param, ae_en)
O(o_test_awb_en, struct isp_test_param, awb_en)
O(o_test_blc_en, struct isp_test_param, blc_en)
O(o_test_wb_en, struct isp_test_param, wb_en)
O(o_test_lsc_en, struct isp_test_param, lsc_en)
O(o_test_msc_en, struct isp_test_param, msc_en)
O(o_test_ccm_en, struct isp_test_param, ccm_en)
O(o_test_gamma_en, struct isp_test_param, gamma_en)
O(o_test_manual_en, struct isp_test_param, manual_en)
O(o_3a_awb_interval, struct isp_3a_param, awb_interval)
O(o_3a_awb_ct_low, struct isp_3a_param, awb_color_temper_low)
O(o_3a_awb_ct_high, struct isp_3a_param, awb_color_temper_high)
O(o_3a_awb_base, struct isp_3a_param, awb_base_temper)
O(o_3a_awb_light_num, struct isp_3a_param, awb_light_num)
O(o_3a_awb_ext_light_num, struct isp_3a_param, awb_ext_light_num)
O(o_3a_awb_skin_num, struct isp_3a_param, awb_skin_color_num)
O(o_3a_awb_special_num, struct isp_3a_param, awb_special_color_num)
O(o_3a_awb_light_info, struct isp_3a_param, awb_light_info)
O(o_3a_awb_ext_light_info, struct isp_3a_param, awb_ext_light_info)
O(o_3a_awb_skin_info, struct isp_3a_param, awb_skin_color_info)
O(o_3a_awb_special_info, struct isp_3a_param, awb_special_color_info)
O(o_3a_awb_preset_gain, struct isp_3a_param, awb_preset_gain)
O(o_3a_awb_rgain_favor, struct isp_3a_param, awb_rgain_favor)
O(o_3a_ae_table_video, struct isp_3a_param, ae_table_video)
O(o_3a_ae_table_video_len, struct isp_3a_param, ae_table_video_length)
O(o_3a_ae_table_preview, struct isp_3a_param, ae_table_preview)
O(o_3a_ae_table_preview_len, struct isp_3a_param, ae_table_preview_length)
O(o_3a_ae_gain_range, struct isp_3a_param, ae_gain_range)
O(o_3a_ae_analog_gain_range, struct isp_3a_param, ae_analog_gain_range)
O(o_3a_ae_max_lv, struct isp_3a_param, ae_max_lv)
O(o_tune_bayer_gain, struct isp_tunning_param, bayer_gain)
O(o_tune_gamma_tbl, struct isp_tunning_param, gamma_tbl_ini)
O(o_tune_gamma_trig, struct isp_tunning_param, gamma_trig_cfg)
O(o_tune_gamma_num, struct isp_tunning_param, gamma_num)
O(o_tune_ccm, struct isp_tunning_param, color_matrix_ini)
O(o_tune_ccm_trig, struct isp_tunning_param, ccm_trig_cfg)
O(o_tune_lsc_trig, struct isp_tunning_param, lsc_trig_cfg)
O(o_iso_lum_map, struct isp_dynamic_param, isp_lum_mapping_point)
O(o_iso_gain_map, struct isp_dynamic_param, isp_gain_mapping_point)
O(o_iso_cfg, struct isp_dynamic_param, isp_dynamic_cfg)
O(o_dyn_black_level, struct isp_dynamic_config, black_level)
O(o_dyn_brightness, struct isp_dynamic_config, brightness)
O(o_dyn_contrast, struct isp_dynamic_config, contrast)
O(o_dyn_cem_cfg, struct isp_dynamic_config, cem_cfg)
O(o_dyn_shading_comp, struct isp_dynamic_config, shading_comp)
